import { authLocalization } from "@neondatabase/auth/react"

export const esLocalization = {
  ...authLocalization,

  // ── Core auth flow ────────────────────────────────────────────────
  MAGIC_LINK: "Bienvenido a Polso",
  MAGIC_LINK_DESCRIPTION: "Inicia sesión o crea una cuenta",
  MAGIC_LINK_ACTION: "Continuar",
  MAGIC_LINK_EMAIL: "Revisa tu correo — te enviamos un enlace de acceso.",
  DISABLED_CREDENTIALS_DESCRIPTION: "Introduce tu email para continuar",

  EMAIL_OTP: "Código por email",
  EMAIL_OTP_DESCRIPTION: "Introduce tu email para recibir un código",
  EMAIL_OTP_SEND_ACTION: "Continuar",
  EMAIL_OTP_VERIFY_ACTION: "Verificar",
  EMAIL_OTP_VERIFICATION_SENT: "Revisa tu correo — te enviamos el código de verificación.",

  SIGN_IN: "Bienvenido a Polso",
  SIGN_IN_ACTION: "Continuar",
  SIGN_IN_DESCRIPTION: "Inicia sesión o crea una cuenta",
  SIGN_IN_WITH: "Continuar con",
  SIGN_OUT: "Cerrar sesión",
  SIGN_UP: "Crear cuenta",
  SIGN_UP_ACTION: "Crear una cuenta",
  SIGN_UP_DESCRIPTION: "Introduce tus datos para crear una cuenta",
  SIGN_UP_EMAIL: "Revisa tu correo para verificar tu cuenta.",

  // ── Common fields ─────────────────────────────────────────────────
  EMAIL: "Email",
  EMAIL_PLACEHOLDER: "tu@empresa.com",
  EMAIL_REQUIRED: "El email es obligatorio",
  EMAIL_DESCRIPTION: "Introduce el email con el que quieres acceder.",
  EMAIL_INSTRUCTIONS: "Introduce una dirección de email válida.",
  EMAIL_IS_THE_SAME: "El email es el mismo",
  EMAIL_VERIFY_CHANGE: "Revisa tu correo para verificar el cambio.",
  EMAIL_VERIFICATION: "Revisa tu correo para el enlace de verificación.",

  NAME: "Nombre",
  NAME_PLACEHOLDER: "Tu nombre",
  NAME_DESCRIPTION: "Introduce tu nombre completo o un nombre de usuario.",
  NAME_INSTRUCTIONS: "Máximo 32 caracteres.",

  PASSWORD: "Contraseña",
  PASSWORD_PLACEHOLDER: "Contraseña",
  PASSWORD_REQUIRED: "La contraseña es obligatoria",
  PASSWORDS_DO_NOT_MATCH: "Las contraseñas no coinciden",
  NEW_PASSWORD: "Nueva contraseña",
  NEW_PASSWORD_PLACEHOLDER: "Nueva contraseña",
  NEW_PASSWORD_REQUIRED: "La nueva contraseña es obligatoria",
  CURRENT_PASSWORD: "Contraseña actual",
  CURRENT_PASSWORD_PLACEHOLDER: "Contraseña actual",
  CONFIRM_PASSWORD: "Confirmar contraseña",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar contraseña",
  CONFIRM_PASSWORD_REQUIRED: "Confirma tu contraseña",

  CONTINUE: "Continuar",
  CANCEL: "Cancelar",
  UPDATE: "Actualizar",
  DELETE: "Eliminar",
  SAVE: "Guardar",
  DONE: "Listo",
  LINK: "Vincular",
  UNLINK: "Desvincular",
  REVOKE: "Revocar",
  ACCEPT: "Aceptar",
  REJECT: "Rechazar",
  OR_CONTINUE_WITH: "o",

  IS_INVALID: "no es válido",
  IS_REQUIRED: "es obligatorio",
  IS_THE_SAME: "es el mismo",
  OPTIONAL_BRACKETS: "(Opcional)",

  GO_BACK: "Volver",
  UNKNOWN: "Desconocido",

  // ── Account ───────────────────────────────────────────────────────
  APP: "App",
  ACCOUNT: "Cuenta",
  ACCOUNTS: "Cuentas",
  ACCOUNTS_DESCRIPTION: "Cambia entre las cuentas en las que has iniciado sesión.",
  ACCOUNTS_INSTRUCTIONS: "Inicia sesión en una cuenta adicional.",
  ADD_ACCOUNT: "Añadir cuenta",
  CURRENT_SESSION: "Sesión actual",
  PERSONAL_ACCOUNT: "Cuenta personal",
  SETTINGS: "Configuración",
  SECURITY: "Seguridad",
  SWITCH_ACCOUNT: "Cambiar cuenta",
  USER: "Usuario",

  // ── Avatar & logo ─────────────────────────────────────────────────
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION: "Haz clic en el avatar para subir uno desde tus archivos.",
  AVATAR_INSTRUCTIONS: "El avatar es opcional pero muy recomendable.",
  DELETE_AVATAR: "Eliminar avatar",
  UPLOAD_AVATAR: "Subir avatar",
  LOGO: "Logo",
  LOGO_DESCRIPTION: "Haz clic en el logo para subir uno desde tus archivos.",
  LOGO_INSTRUCTIONS: "El logo es opcional pero muy recomendable.",
  UPLOAD: "Subir",
  UPLOAD_LOGO: "Subir logo",
  DELETE_LOGO: "Eliminar logo",

  // ── Password management ───────────────────────────────────────────
  CHANGE_PASSWORD: "Cambiar contraseña",
  CHANGE_PASSWORD_DESCRIPTION: "Introduce tu contraseña actual y una nueva contraseña.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Mínimo 8 caracteres.",
  CHANGE_PASSWORD_SUCCESS: "Tu contraseña ha sido cambiada.",
  FORGOT_PASSWORD: "Restablecer contraseña",
  FORGOT_PASSWORD_ACTION: "Enviar enlace",
  FORGOT_PASSWORD_DESCRIPTION: "Introduce tu email para restablecer tu contraseña",
  FORGOT_PASSWORD_EMAIL: "Revisa tu correo para el enlace de restablecimiento.",
  FORGOT_PASSWORD_LINK: "¿Olvidaste tu contraseña?",
  SET_PASSWORD: "Establecer contraseña",
  SET_PASSWORD_DESCRIPTION: "Haz clic en el botón para recibir un email y establecer una contraseña.",
  RESET_PASSWORD: "Restablecer contraseña",
  RESET_PASSWORD_ACTION: "Guardar nueva contraseña",
  RESET_PASSWORD_DESCRIPTION: "Introduce tu nueva contraseña",
  RESET_PASSWORD_SUCCESS: "Contraseña restablecida correctamente",

  // ── Account deletion ──────────────────────────────────────────────
  DELETE_ACCOUNT: "Eliminar cuenta",
  DELETE_ACCOUNT_DESCRIPTION: "Elimina permanentemente tu cuenta y todo su contenido. Esta acción no se puede deshacer.",
  DELETE_ACCOUNT_INSTRUCTIONS: "Confirma la eliminación de tu cuenta. Esta acción no se puede deshacer.",
  DELETE_ACCOUNT_VERIFY: "Revisa tu correo para verificar la eliminación de tu cuenta.",
  DELETE_ACCOUNT_SUCCESS: "Tu cuenta ha sido eliminada.",

  // ── Sessions ──────────────────────────────────────────────────────
  SESSIONS: "Sesiones",
  SESSIONS_DESCRIPTION: "Gestiona tus sesiones activas y revoca el acceso.",
  SESSION_EXPIRED: "Sesión caducada. Vuelve a iniciar sesión.",
  SESSION_NOT_FRESH: "Tu sesión no es reciente. Vuelve a iniciar sesión.",
  REMEMBER_ME: "Recordarme",
  TRUST_DEVICE: "Confiar en este dispositivo",

  // ── Email verification ────────────────────────────────────────────
  VERIFY_YOUR_EMAIL: "Verifica tu email",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Verifica tu dirección de email. Revisa tu bandeja de entrada. Si no has recibido el email, haz clic abajo para reenviarlo.",
  RESEND_VERIFICATION_EMAIL: "Reenviar email de verificación",
  SEND_VERIFICATION_CODE: "Enviar código de verificación",
  RESEND_CODE: "Reenviar código",
  UPDATED_SUCCESSFULLY: "actualizado correctamente",

  // ── Two-factor auth ───────────────────────────────────────────────
  TWO_FACTOR: "Doble factor",
  TWO_FACTOR_ACTION: "Verificar código",
  TWO_FACTOR_DESCRIPTION: "Introduce tu contraseña de un solo uso para continuar",
  TWO_FACTOR_CARD_DESCRIPTION: "Añade una capa extra de seguridad a tu cuenta.",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Introduce tu contraseña para desactivar el 2FA.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Introduce tu contraseña para activar el 2FA.",
  TWO_FACTOR_ENABLED: "La autenticación de doble factor ha sido activada",
  TWO_FACTOR_DISABLED: "La autenticación de doble factor ha sido desactivada",
  TWO_FACTOR_PROMPT: "Autenticación de doble factor",
  TWO_FACTOR_TOTP_LABEL: "Escanea el código QR con tu aplicación de autenticación",
  ENABLE_TWO_FACTOR: "Activar doble factor",
  DISABLE_TWO_FACTOR: "Desactivar doble factor",
  ONE_TIME_PASSWORD: "Contraseña de un solo uso",
  CONTINUE_WITH_AUTHENTICATOR: "Continuar con autenticador",
  FORGOT_AUTHENTICATOR: "¿Olvidaste el autenticador?",

  // ── Backup codes ──────────────────────────────────────────────────
  BACKUP_CODES: "Códigos de respaldo",
  BACKUP_CODES_DESCRIPTION: "Guarda estos códigos en un lugar seguro. Úsalos si pierdes el acceso al autenticador.",
  BACKUP_CODE: "Código de respaldo",
  BACKUP_CODE_PLACEHOLDER: "Código de respaldo",
  BACKUP_CODE_REQUIRED: "El código de respaldo es obligatorio",
  COPY_ALL_CODES: "Copiar todos los códigos",
  COPY_TO_CLIPBOARD: "Copiar al portapapeles",
  COPIED_TO_CLIPBOARD: "Copiado al portapapeles",
  RECOVER_ACCOUNT: "Recuperar cuenta",
  RECOVER_ACCOUNT_ACTION: "Recuperar cuenta",
  RECOVER_ACCOUNT_DESCRIPTION: "Introduce un código de respaldo para acceder a tu cuenta",

  // ── Passkeys ──────────────────────────────────────────────────────
  PASSKEY: "Passkey",
  PASSKEYS: "Passkeys",
  PASSKEYS_DESCRIPTION: "Gestiona tus passkeys para un acceso seguro.",
  PASSKEYS_INSTRUCTIONS: "Accede a tu cuenta de forma segura sin contraseña.",
  ADD_PASSKEY: "Añadir passkey",

  // ── Providers / social ────────────────────────────────────────────
  PROVIDERS: "Proveedores",
  PROVIDERS_DESCRIPTION: "Conecta tu cuenta con un servicio externo.",

  // ── API keys ──────────────────────────────────────────────────────
  API_KEYS: "Claves API",
  API_KEYS_DESCRIPTION: "Gestiona tus claves API para acceso seguro.",
  API_KEYS_INSTRUCTIONS: "Genera claves API para acceder a tu cuenta de forma programática.",
  CREATE_API_KEY: "Crear clave API",
  CREATE_API_KEY_DESCRIPTION: "Introduce un nombre único para distinguir esta clave.",
  API_KEY_NAME_PLACEHOLDER: "Nueva clave API",
  API_KEY_CREATED: "Clave API creada",
  CREATE_API_KEY_SUCCESS: "Copia tu clave API y guárdala en un lugar seguro. Por seguridad, no podremos volvértela a mostrar.",
  API_KEY: "Clave API",
  DELETE_API_KEY: "Eliminar clave API",
  DELETE_API_KEY_CONFIRM: "¿Seguro que quieres eliminar esta clave API?",
  NEVER_EXPIRES: "Sin caducidad",
  EXPIRES: "Caduca",
  NO_EXPIRATION: "Sin caducidad",

  // ── Organization ──────────────────────────────────────────────────
  CREATE_ORGANIZATION: "Crear organización",
  ORGANIZATION: "Organización",
  ORGANIZATION_NAME: "Nombre",
  ORGANIZATION_NAME_PLACEHOLDER: "Empresa S.L.",
  ORGANIZATION_NAME_DESCRIPTION: "El nombre visible de tu organización.",
  ORGANIZATION_NAME_INSTRUCTIONS: "Máximo 32 caracteres.",
  ORGANIZATION_SLUG: "URL slug",
  ORGANIZATION_SLUG_DESCRIPTION: "El espacio de nombres de URL de tu organización.",
  ORGANIZATION_SLUG_INSTRUCTIONS: "Máximo 48 caracteres.",
  ORGANIZATION_SLUG_PLACEHOLDER: "empresa-sl",
  CREATE_ORGANIZATION_SUCCESS: "Organización creada correctamente",
  ORGANIZATIONS: "Organizaciones",
  ORGANIZATIONS_DESCRIPTION: "Gestiona tus organizaciones y membresías.",
  ORGANIZATIONS_INSTRUCTIONS: "Crea una organización para colaborar con otros usuarios.",
  LEAVE_ORGANIZATION: "Abandonar organización",
  LEAVE_ORGANIZATION_CONFIRM: "¿Seguro que quieres abandonar esta organización?",
  LEAVE_ORGANIZATION_SUCCESS: "Has abandonado la organización correctamente.",
  MANAGE_ORGANIZATION: "Gestionar organización",
  DELETE_ORGANIZATION: "Eliminar organización",
  DELETE_ORGANIZATION_DESCRIPTION: "Elimina permanentemente tu organización y todo su contenido. Esta acción no se puede deshacer.",
  DELETE_ORGANIZATION_SUCCESS: "Organización eliminada correctamente",
  DELETE_ORGANIZATION_INSTRUCTIONS: "Introduce el slug de la organización para continuar:",
  SLUG_REQUIRED: "El slug de la organización es obligatorio",
  SLUG_DOES_NOT_MATCH: "El slug no coincide",

  // ── Members & invitations ─────────────────────────────────────────
  MEMBERS: "Miembros",
  MEMBERS_DESCRIPTION: "Añade o elimina miembros y gestiona sus roles.",
  MEMBERS_INSTRUCTIONS: "Invita nuevos miembros a tu organización.",
  REMOVE_MEMBER: "Eliminar miembro",
  REMOVE_MEMBER_CONFIRM: "¿Seguro que quieres eliminar a este miembro de la organización?",
  REMOVE_MEMBER_SUCCESS: "Miembro eliminado correctamente",
  INVITE_MEMBER: "Invitar miembro",
  INVITE_MEMBER_DESCRIPTION: "Envía una invitación para añadir un nuevo miembro a tu organización.",
  ROLE: "Rol",
  SELECT_ROLE: "Seleccionar rol",
  ADMIN: "Administrador",
  MEMBER: "Miembro",
  GUEST: "Invitado",
  OWNER: "Propietario",
  UPDATE_ROLE_DESCRIPTION: "Actualiza el rol de este miembro",
  UPDATE_ROLE: "Actualizar rol",
  MEMBER_ROLE_UPDATED: "Rol del miembro actualizado correctamente",
  SEND_INVITATION: "Enviar invitación",
  SEND_INVITATION_SUCCESS: "Invitación enviada correctamente",
  PENDING_INVITATIONS: "Invitaciones pendientes",
  PENDING_INVITATIONS_DESCRIPTION: "Gestiona las invitaciones pendientes a tu organización.",
  PENDING_USER_INVITATIONS_DESCRIPTION: "Invitaciones que has recibido de organizaciones.",
  CANCEL_INVITATION: "Cancelar invitación",
  INVITATION_CANCELLED: "Invitación cancelada correctamente",
  ACCEPT_INVITATION: "Aceptar invitación",
  ACCEPT_INVITATION_DESCRIPTION: "Has sido invitado a unirte a una organización.",
  INVITATION_ACCEPTED: "Invitación aceptada correctamente",
  INVITATION_REJECTED: "Invitación rechazada correctamente",
  INVITATION_EXPIRED: "Esta invitación ha caducado",
  MEMBER_SINGULAR: "miembro",
  MEMBER_PLURAL: "miembros",
  DONT_HAVE_AN_ACCOUNT: "¿No tienes cuenta?",
  ALREADY_HAVE_AN_ACCOUNT: "¿Ya tienes cuenta?",

  // ── Teams ─────────────────────────────────────────────────────────
  TEAM: "Equipo",
  TEAMS: "Equipos",
  TEAM_ACTIVE: "Activo",
  TEAM_SET_ACTIVE: "Establecer activo",
  CREATE_TEAM: "Crear equipo",
  CREATE_TEAM_SUCCESS: "Equipo creado correctamente",
  UPDATE_TEAM: "Actualizar equipo",
  UPDATE_TEAM_DESCRIPTION: "Actualiza el nombre de este equipo",
  UPDATE_TEAM_SUCCESS: "Equipo actualizado correctamente",
  REMOVE_TEAM_CONFIRM: "¿Seguro que quieres eliminar este equipo de la organización?",
  CREATE_TEAM_INSTRUCTIONS: "Añade un nuevo equipo a tu organización.",
  TEAM_NAME: "Nombre del equipo",
  TEAM_NAME_PLACEHOLDER: "Equipo de Ingeniería",
  TEAM_NAME_DESCRIPTION: "El nombre visible de tu equipo.",
  TEAM_NAME_INSTRUCTIONS: "Máximo 64 caracteres.",
  TEAMS_DESCRIPTION: "Gestiona tus equipos dentro de tu organización.",
  USER_TEAMS_DESCRIPTION: "Eres miembro de los siguientes equipos.",
  DELETE_TEAM: "Eliminar equipo",
  DELETE_TEAM_DESCRIPTION: "Elimina permanentemente este equipo y todo su contenido.",
  DELETE_TEAM_SUCCESS: "Equipo eliminado correctamente",
  DELETE_TEAM_INSTRUCTIONS: "Introduce el nombre del equipo para continuar:",
  TEAM_NAME_REQUIRED: "El nombre del equipo es obligatorio",
  TEAM_NAME_DOES_NOT_MATCH: "El nombre del equipo no coincide",
  TEAM_MEMBERS: "Miembros del equipo",
  TEAM_MEMBERS_DESCRIPTION: "Gestiona los miembros de tu equipo y sus roles.",
  ADD_TEAM_MEMBER: "Añadir miembro",
  REMOVE_TEAM_MEMBER: "Eliminar miembro",
  REMOVE_TEAM_MEMBER_CONFIRM: "¿Seguro que quieres eliminar a este miembro del equipo?",
  REMOVE_TEAM_MEMBER_SUCCESS: "Miembro eliminado del equipo correctamente",
  ADD_TEAM_MEMBER_SUCCESS: "Miembro añadido al equipo correctamente",
  MANAGE_TEAM_MEMBERS: "Gestionar miembros",
  MANAGE_TEAM_MEMBERS_DESCRIPTION: "Busca y añade miembros de la organización a este equipo.",
  NO_TEAMS_FOUND: "No se encontraron equipos",

  // ── Legal ─────────────────────────────────────────────────────────
  PRIVACY_POLICY: "Política de privacidad",
  TERMS_OF_SERVICE: "Términos de servicio",
  BY_CONTINUING_YOU_AGREE: "Al continuar, aceptas los",
  PROTECTED_BY_RECAPTCHA: "Este sitio está protegido por reCAPTCHA.",

  // ── Username ──────────────────────────────────────────────────────
  USERNAME: "Usuario",
  USERNAME_DESCRIPTION: "Introduce el nombre de usuario con el que quieres acceder.",
  USERNAME_INSTRUCTIONS: "Máximo 32 caracteres.",
  USERNAME_PLACEHOLDER: "Usuario",
  SIGN_IN_USERNAME_DESCRIPTION: "Introduce tu usuario o email para acceder",
  SIGN_IN_USERNAME_PLACEHOLDER: "Usuario o email",

  // ── Error messages ────────────────────────────────────────────────
  REQUEST_FAILED: "La solicitud ha fallado",
  UNKNOWN_ERROR: "Algo ha ido mal",
  UNEXPECTED_ERROR: "Error inesperado",
  INVALID_EMAIL: "Email no válido",
  INVALID_EMAIL_OR_PASSWORD: "Email o contraseña incorrectos",
  INVALID_PASSWORD: "Contraseña incorrecta",
  INVALID_TOKEN: "Token no válido",
  INVALID_OTP: "Código no válido",
  INVALID_CODE: "Código no válido",
  INVALID_BACKUP_CODE: "Código de respaldo no válido",
  OTP_EXPIRED: "El código ha caducado",
  OTP_HAS_EXPIRED: "El código ha caducado",
  OTP_NOT_FOUND: "Código no encontrado",
  TOO_MANY_ATTEMPTS: "Demasiados intentos",
  TOO_MANY_ATTEMPTS_REQUEST_NEW_CODE: "Demasiados intentos. Solicita un nuevo código.",
  RATE_LIMIT_EXCEEDED: "Límite de solicitudes superado.",
  USER_ALREADY_EXISTS: "Este email ya está registrado",
  USER_NOT_FOUND: "Usuario no encontrado",
  ACCOUNT_NOT_FOUND: "Cuenta no encontrada",
  EMAIL_NOT_VERIFIED: "Email no verificado",
  PASSWORD_TOO_SHORT: "La contraseña es demasiado corta",
  PASSWORD_TOO_LONG: "La contraseña es demasiado larga",
  SOCIAL_ACCOUNT_ALREADY_LINKED: "La cuenta social ya está vinculada",
  PROVIDER_NOT_FOUND: "Proveedor no encontrado",
  FAILED_TO_UNLINK_LAST_ACCOUNT: "No puedes desvincular tu última cuenta",
  BANNED_USER: "Tu cuenta ha sido bloqueada",
  ORGANIZATION_NOT_FOUND: "Organización no encontrada",
  ORGANIZATION_ALREADY_EXISTS: "La organización ya existe",
  MEMBER_NOT_FOUND: "Miembro no encontrado",
  INVITATION_NOT_FOUND: "Invitación no encontrada",
  TEAM_NOT_FOUND: "Equipo no encontrado",
  KEY_NOT_FOUND: "Clave API no encontrada",
  KEY_DISABLED: "La clave API está desactivada",
  KEY_EXPIRED: "La clave API ha caducado",
  USAGE_EXCEEDED: "La clave API ha alcanzado su límite de uso",
  AUTHENTICATION_FAILED: "Autenticación fallida",
  VERIFICATION_FAILED: "Verificación fallida",
  CHALLENGE_NOT_FOUND: "Desafío no encontrado",
  PASSKEY_NOT_FOUND: "Passkey no encontrada",
}
